// File generated by FlutterFire CLI
// https://github.com/firebase/flutterfire/tree/main/packages/firebase_core/firebase_core_platform_interface/lib/src/method_channel

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// Platform-specific Firebase configuration options
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEoBS-5hfye1VYMhjEoRPv1gu3XBcblhA',
    appId: '1:502383251544:android:dcd449198b8bb2c00e7a2d',
    messagingSenderId: '502383251544',
    projectId: 'reclaim-c222a',
    databaseURL: 'https://reclaim-c222a.firebaseio.com',
    storageBucket: 'reclaim-c222a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEoBS-5hfye1VYMhjEoRPv1gu3XBcblhA',
    appId: '1:502383251544:ios:dcd449198b8bb2c00e7a2d',
    messagingSenderId: '502383251544',
    projectId: 'reclaim-c222a',
    databaseURL: 'https://reclaim-c222a.firebaseio.com',
    storageBucket: 'reclaim-c222a.firebasestorage.app',
    iosBundleId: 'com.reclaim.reclaim',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEoBS-5hfye1VYMhjEoRPv1gu3XBcblhA',
    appId: '1:502383251544:web:dcd449198b8bb2c00e7a2d',
    messagingSenderId: '502383251544',
    projectId: 'reclaim-c222a',
    databaseURL: 'https://reclaim-c222a.firebaseio.com',
    storageBucket: 'reclaim-c222a.firebasestorage.app',
    authDomain: 'reclaim-c222a.firebaseapp.com',
  );
}
